# Generated by Django 4.1.4 on 2023-01-01 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_writer', models.BooleanField(default=False)),
                ('is_reader', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('age', models.IntegerField(choices=[(0, 'Select Your Age Range'), (1, '0-12 years'), (2, '13-19 years'), (3, '20 years and above')], default=0)),
                ('state', models.IntegerField(choices=[(0, 'Select State'), (1, 'Abia'), (2, 'Adamawa'), (3, 'Akwa Ibom'), (4, 'Anambra'), (5, 'Bauchi'), (6, 'Bayelsa'), (7, 'Benue'), (8, 'Borno'), (9, 'Cross River'), (10, 'Delta'), (11, 'Ebonyi'), (12, 'Edo'), (13, 'Ekiti'), (14, 'Enugu'), (15, 'Gombe'), (16, 'Imo'), (17, 'Jigawa'), (18, 'Kaduna'), (19, 'Kano'), (20, 'Katsina'), (21, 'Kebbi'), (22, 'Kogi'), (23, 'Kwara'), (24, 'Lagos'), (25, 'Nasarawa'), (26, 'Niger'), (27, 'Ogun'), (28, 'Ondo'), (29, 'Osun'), (30, 'Oyo'), (31, 'Plateau'), (32, 'Rivers'), (33, 'Sokoto'), (34, 'Taraba'), (35, 'Yobe'), (36, 'Zamfara'), (37, 'FCT')], default=0)),
                ('home_address', models.CharField(max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('blog', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogmodel')),
                ('owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
